# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: /home/delorenj/.local/share/mise/installs/node/26.5.0/lib/node_modules/@delorenj/pjangler/templates/commonproject
project_description: Ingress for audio to be transcribed
project_name: transcription-queue
ticket_provider: plane
